import { useEffect, useState } from 'react'
import { Activity, BusFront, CircleDollarSign, Clock3, Menu, Users } from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { getDashboard } from '../services/api'
import RouteMap from '../components/RouteMap'

const palette = ['#d7438f', '#00c875', '#f0a227', '#4f46e5']
const number = new Intl.NumberFormat('es-MX')
const currency = new Intl.NumberFormat('es-MX', { style: 'currency', currency: 'MXN', maximumFractionDigits: 0 })
function Card({ icon: Icon, label, value, detail, color }) { return <article className="rounded-[2rem] bg-white p-6 shadow-sm ring-1 ring-slate-100"><div className="flex items-start justify-between"><p className="text-sm font-bold uppercase tracking-wider text-slate-400">{label}</p><span className="rounded-full bg-slate-50 p-3" style={{ color }}><Icon size={22} /></span></div><p className="mt-8 text-4xl font-extrabold tracking-tight" style={{ color }}>{value}</p><p className="mt-3 text-xs font-bold uppercase tracking-wide text-slate-600">{detail}</p></article> }
function Panel({ title, children, className = '' }) { return <section className={`rounded-[2rem] bg-white p-6 shadow-sm ring-1 ring-slate-100 ${className}`}><h2 className="mb-5 text-xl font-bold text-slate-800">{title}</h2>{children}</section> }

export default function DashboardPage({ focus = 'dashboard' }) {
  const [route, setRoute] = useState('Todas'); const [period, setPeriod] = useState('Todos'); const [data, setData] = useState(null); const [error, setError] = useState('')
  useEffect(() => { setData(null); getDashboard({ route, period }).then(setData).catch(() => setError('No fue posible conectar con la API. Inicia el backend en el puerto 8000.')) }, [route, period])
  if (error) return <div className="rounded-2xl bg-rose-50 p-6 text-rose-700">{error}</div>
  if (!data) return <div className="py-24 text-center font-semibold text-slate-500">Cargando información operativa…</div>
  const s = data.summary; const savings = Array.isArray(data.ahorro_economico) ? data.ahorro_economico : []; const show = (section) => focus === 'dashboard' || focus === section
  return <div className="space-y-7">
    <section className="flex flex-col gap-4 rounded-[2rem] bg-white p-5 shadow-sm ring-1 ring-slate-100 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-3 rounded-xl bg-indigo-50 px-4 py-3 text-sm font-bold text-indigo-600"><Menu size={18} /> Filtros y búsqueda</div><div className="flex flex-wrap gap-3"><select value={route} onChange={(e) => setRoute(e.target.value)} className="rounded-xl border-0 bg-slate-100 px-4 py-3 font-medium text-slate-700"><option>Todas</option><option>Ruta 1</option><option>Ruta 2</option></select><select value={period} onChange={(e) => setPeriod(e.target.value)} className="rounded-xl border-0 bg-slate-100 px-4 py-3 font-medium text-slate-700"><option>Todos</option><option>Torito</option><option>Rancho Viejo</option></select></div></section>
    {show('dashboard') && <><section className="grid gap-5 md:grid-cols-2 xl:grid-cols-5"><Card icon={Users} label="Ascensos totales" value={number.format(s.ascensos_totales)} detail={`${number.format(s.promedio_diario)} pasajeros al día`} color={palette[0]} /><Card icon={BusFront} label="Corridas registradas" value={number.format(s.corridas)} detail={`${s.dias_operados} días operados`} color={palette[1]} /><Card icon={CircleDollarSign} label="Ahorro estimado" value={currency.format(s.ahorro_estimado ?? 0)} detail={`${currency.format(s.tarifa_referencia ?? 12)} por ascenso`} color="#00a96b" /><Card icon={Clock3} label="Puntualidad" value={`${s.puntualidad}%`} detail="Llegadas dentro de ±5 min" color={palette[2]} /><Card icon={Activity} label="Desviación media" value={`${s.desviacion_promedio > 0 ? '+' : ''}${s.desviacion_promedio} min`} detail="Real frente a programado" color={palette[3]} /></section><Panel title="Ahorro económico estimado por ruta histórica"><p className="-mt-3 mb-4 text-sm text-slate-500">Equivalente a ascensos registrados × tarifa de referencia de $12 MXN; no representa ingresos del servicio.</p><div className="h-72"><ResponsiveContainer><PieChart><Pie data={savings} dataKey="ahorro_estimado" nameKey="ruta" innerRadius={58} outerRadius={95} paddingAngle={3}>{savings.map((item, index) => <Cell key={item.ruta} fill={palette[index % palette.length]} />)}</Pie><Tooltip formatter={(value) => currency.format(value)} /><Legend /></PieChart></ResponsiveContainer></div></Panel></>}
    {show('demanda') && <div className="grid gap-7 xl:grid-cols-5"><Panel title="Tendencia de demanda" className="xl:col-span-3"><div className="h-80"><ResponsiveContainer><AreaChart data={data.tendencia}><defs><linearGradient id="demand" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#00c875" stopOpacity=".35"/><stop offset="100%" stopColor="#00c875" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e2e8f0"/><XAxis dataKey="fecha" hide/><YAxis/><Tooltip/><Area type="monotone" dataKey="ascensos" stroke="#00b968" strokeWidth={3} fill="url(#demand)" /></AreaChart></ResponsiveContainer></div></Panel><Panel title="Demanda por horario" className="xl:col-span-2"><div className="h-80"><ResponsiveContainer><BarChart data={data.demanda_horaria}><XAxis dataKey="hora" hide/><Tooltip/><Bar dataKey="ascensos" fill="#d7438f" radius={[5,5,0,0]} /></BarChart></ResponsiveContainer></div></Panel></div>}
    {show('ocupacion') && <Panel title="Máxima ocupación acumulada por paradero"><p className="-mt-3 mb-4 text-sm text-slate-500">Mayor carga registrada después de cada parada, con los filtros activos.</p><div className="h-80"><ResponsiveContainer><BarChart data={data.ocupacion} layout="vertical" margin={{ left: 65 }}><XAxis type="number"/><YAxis type="category" dataKey="paradero" width={170} tick={{ fontSize: 11 }}/><Tooltip/><Bar dataKey="ocupacion" fill="#4f46e5" radius={[0,6,6,0]} /></BarChart></ResponsiveContainer></div></Panel>}
    {show('tiempo') && <Panel title="Tiempo completo de recorrido por ruta"><p className="-mt-3 mb-4 text-sm text-slate-500">Minutos entre el primer y último registro real de cada corrida.</p><div className="grid gap-4 md:grid-cols-2">{data.tiempos.map((item, index) => <div key={item.ruta} className="rounded-2xl bg-slate-50 p-5"><p className="font-bold" style={{ color: palette[index] }}>{item.ruta}</p><p className="mt-3 text-3xl font-extrabold text-slate-800">{item.promedio} min</p><p className="mt-2 text-sm text-slate-500">Rango: {item.minimo}–{item.maximo} min · mediana {item.mediana}</p></div>)}</div></Panel>}
    {show('cobertura') && <Panel title="Paraderos con mayor movimiento de pasajeros"><p className="-mt-3 mb-4 text-sm text-slate-500">Generador: predominan ascensos; atraíble: predominan descensos.</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-slate-400"><tr><th className="pb-3">Paradero</th><th>Tipo</th><th>Ascensos</th><th>Descensos</th></tr></thead><tbody>{data.paraderos.map((stop) => <tr key={stop.paradero} className="border-b border-slate-100"><td className="py-3 font-medium">{stop.paradero.replace('Paradero ', '')}</td><td><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-600">{stop.tipo}</span></td><td>{number.format(stop.ascensos)}</td><td>{number.format(stop.descensos)}</td></tr>)}</tbody></table></div></Panel>}
    {show('comparacion') && <div className="grid gap-7 lg:grid-cols-2"><Panel title="Transición Ruta 1: pasajeros por día">{data.transicion_ruta_1.periodos.map((item, index) => <div key={item.periodo} className="mb-4 rounded-2xl bg-slate-50 p-5"><p className="font-bold" style={{ color: palette[index] }}>{item.periodo}</p><p className="mt-2 text-3xl font-extrabold">{item.promedio_diario}</p><p className="text-sm text-slate-500">ascensos promedio por día</p></div>)}</Panel><Panel title="Demanda captada en nuevos paraderos">{data.transicion_ruta_1.nuevos_paraderos.map((item) => <div key={item.paradero} className="flex items-center justify-between border-b border-slate-100 py-4"><span className="font-medium">{item.paradero.replace('Paradero ', '')}</span><span className="font-extrabold text-emerald-600">{number.format(item.ascensos)}</span></div>)}</Panel></div>}
    {focus === 'mapa' && <Panel title="Distribución espacial de rutas"><p className="mb-5 text-sm text-slate-500"><span className="font-bold text-pink-600">Ruta 1</span> · Rancho Viejo y Zona Hotelera &nbsp; <span className="font-bold text-emerald-600">Ruta 2</span> · Tres Reyes, Tierra Maya, Kusamil y Zona Hotelera</p><RouteMap /></Panel>}
  </div>
}
